<?php
namespace app\component;
use yii\web\Controller;
use yii;
/**
 * Created by PhpStorm.
 * User: china
 * Date: 2016/12/1
 * Time: 16:34
 */
class BaseController extends Controller
{
	public $enableCsrfValidation = false;
	public $result_format = 'json';
	public $result = ['result'=>'', 'data'=>'', 'msg'=>''];

	public function beforeAction($action)
	{
		$request = Yii::$app->request;
		$dataType = $request->get('dataType')?$request->get('dataType'):'json';
		$this->result_format = $dataType;
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	public function successResult($data)
	{
		$this->setResult($data);
		$this->result['result'] = true;
		return $this->pushResult();
	}

	public function errorResult($data)
	{
		$this->setResult($data);
		$this->result['result'] = false;
		return $this->pushResult();
	}
	public function setResult($data)
	{
		if (is_array($data))
			$this->result = $data;
		else
			$this->result['msg'] = $data;
	}
	public function pushResult()
	{
		switch ($this->result_format)
		{
			case 'json':
				return $this->jsonResult($this->result);
			case 'xml':
				return $this->xmlResult($this->result);
			case 'jsonp':
				return $this->jsonPResult($this->result);
			default:
				return $this->jsonResult($this->result);
		}
	}

	public function jsonResult($data)
	{
		return Yii::$app->response->content = json_encode($data);
	}

	public function xmlResult($data)
	{
		return Yii::$app->response->content = json_encode($data);
	}

	public function jsonPResult($data)
	{
		$request = Yii::$app->request;
		$callback = $request->get('callback', 'callback');
		$callback = htmlspecialchars($callback);
		return Yii::$app->response->content = $callback . "(" . json_encode($data) . ")";
	}

	public function http($url, $data=null)
	{
		$http = new HttpClient();
		$result = $http->httpRequest($url, $data);
		return @json_decode($result, true);
	}
}