<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/8/4
 * Time: 12:05
 */

namespace app\component;


use yii\base\Action;
use yii\web\UploadedFile;
use yii;

class FileUpload extends Action
{
	public $uploadPath;

	public $uploadUrl;
	
	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function run()
	{
		$this->actionUploading();
	}

	public function actionUploading()
	{
		$result = array('result' => false, 'msg' => 'upload is error', 'file' => '', 'temp'=>'');

		$fileTypes = array('image/jpeg', 'image/png');

		$upload = UploadedFile::getInstanceByName($_POST['name']);

		if (!$upload)
		{
			return Yii::$app->response->content = json_encode($result);
		}

		$fileName = md5($upload->getBaseName() . time());

		$showName =  $fileName . '.' . $upload->getExtension();

		$date = date("Y/m")."/";
		$path = Yii::$app->basePath.'/web/upload/'.$date;
		DirectoryHelp::create_dir($path);

		$file = $path . $showName;

		if (is_dir($path) && is_writable($path) && in_array($upload->type, $fileTypes) && ($upload->saveAs($file))) {
			$result['result'] = true;
			$result['file'] = $showName;
			$result['temp'] = "/upload/".$date;
			$result['msg'] = 'success';
		} else {
			$result['result'] = false;
			$result['msg'] = "file upload was fail is_dir:" .
				(is_dir($path) ? "true" : "false") .
				" is_writable:" . (is_writable($path) ? "true" : "false") .
				" type:" . $upload->type .
				" path:".$path;
		}
		return Yii::$app->response->content = json_encode($result);
	}
}